# Generated by Django 2.2.10 on 2020-04-01 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0002_auto_20200331_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='uname',
        ),
        migrations.AddField(
            model_name='instructor',
            name='type',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
