# Generated by Django 2.2.10 on 2020-04-07 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0001_initial'),
        ('instructor', '0003_auto_20200401_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=5000)),
                ('filename', models.CharField(max_length=500)),
                ('filepath', models.ImageField(null=True, upload_to='files/', verbose_name='')),
                ('courseName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Details.Course')),
            ],
        ),
    ]
