# Generated by Django 2.2.10 on 2020-04-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='filepath',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
