# Generated by Django 2.2.10 on 2020-04-20 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0001_initial'),
        ('instructor', '0005_auto_20200407_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000)),
                ('optionA', models.CharField(max_length=250)),
                ('optionB', models.CharField(max_length=250)),
                ('optionC', models.CharField(max_length=250)),
                ('optionD', models.CharField(max_length=250)),
                ('correctOption', models.CharField(max_length=250)),
                ('explanation', models.TextField(max_length=250)),
                ('courseName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Details.Course')),
                ('topicName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instructor.FileUpload')),
            ],
        ),
    ]
