# Generated by Django 2.2.10 on 2020-03-31 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0001_initial'),
        ('instructor', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Details.Batch'),
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Details.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='instructor',
            field=models.ManyToManyField(to='instructor.Instructor'),
        ),
        migrations.AddField(
            model_name='student',
            name='pwd',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='lname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
