# Generated by Django 2.2.10 on 2020-03-31 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
        ('students', '0002_auto_20200331_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='instructor',
        ),
        migrations.AddField(
            model_name='student',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructor.Instructor'),
        ),
    ]
