# Generated by Django 2.2.10 on 2020-03-31 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200331_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lname',
        ),
    ]
