# Generated by Django 2.2.10 on 2020-04-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200331_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
