# Generated by Django 2.2.10 on 2020-04-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20200414_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='type',
            new_name='active',
        ),
    ]
